[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
